s = 'hello World'
print(s.capitalize())
print(s.upper())
print(s.lower())
print(s.swapcase())
print(s.center(20, '*'))
print(s.ljust(20, '*'))
print(s.rjust(20, '*'))
print('hello\tWorld'.expandtabs())
print(len(s))
print(s.startswith('he'))
print(s.endswith('l', 7, -1))
print(s.find('e'))
print(s.index('e'))
print(s.rfind('l'))
print(' hello world '.strip())
print('* hello world *'.rstrip('* '))
print('* hello world *'.lstrip('* '))
print(s.count('l'))
print(s.count('l', 3, 6))
print(s.split())
print('hello world !'.partition(' '))
f1 = 'my name is {}, my age is {}'.format('xu', 18)
print(f1)
f2 = 'my name is {0}, my age is {1}, my name is {0}'.format('xu', 18)
print(f2)
f3 = 'my name is {name}, my age is {age}, my name is {name}'.format(name='xu', age=18)
print(f3)
print(s.replace('l', 'L'))
print(s.replace('l', 'L', 1))
print(s.isalnum())
print(s.isalpha())
print(s.isdecimal())
for i in s:
    print(i, end=' ')
    print()
if 'o' in s:
    print('敏感字符')
